name: clima
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-80.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  geolocator: ^8.2.0
  http: ^0.13.4
  lottie: ^1.2.2
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4


flutter:

  uses-material-design: true
  assets:
    - assets/



